<a href="https://colab.research.google.com/github/EddiRafael/Clase_desarrollo_proyectos/blob/main/1_Extraccion_Datos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Importamos librerias requeridas 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import io

In [ ]:
#cargar archivo csv desde equipo 
from google.colab import files 
files.upload()

In [ ]:
#convertir en dataframe 
df= pd.read_csv("file.csv")
df

In [ ]:
#imprimimos las primeras filas o registros del dataframe 
df.head(5)

In [ ]:
#filtro por objeto 
filtro1=df[df["Entidad_Federativa"]=="Baja California"]
filtro1

In [ ]:
#filtro por filas 
filtro2= df.iloc[0:99,: ]
filtro2=df.iloc[[1000, 2000, 3000], : ]
filtro2

In [ ]:
#filtro por columnas 
#filtro3= df.iloc[ : , 4:6]
filtro3= df.iloc[ : , [1,4,6]] #columnas consecutivas 
filtro3

In [ ]:
#filtro por columnas y filas
filtro_mix= df.iloc[ [10,20,50] , 2:5]
#filtro3= df.iloc[ : , [1,4,6]] #columnas no consecutivas 
filtro_mix

In [20]:
#filtro de filas vs columnas 
#paso 1: leemos el contenido del archivo 
from google.colab import files 
uploaded= files.upload()
df= pd.read_csv(io.BytesIO(uploaded['file.csv']), index_col=2)
df

Saving file.csv to file (2).csv

,Periodo,Trimestre,Sexo,Poblacion_ocupada_en_la_industria_manufacturera,Poblaci n_ocupada,Tasa_de_ocupaci n_en_la_industria_manufacturera
Entidad_Federativa,,,,,,
Nacional,2005,1,Hombres,4384907,26597801,16.485975660000000000000
Nacional,2005,1,Mujeres,2690296,14843275,18.124679360000000000000
Aguascalientes,2005,1,Hombres,56407,246177,22.913188480000000000000
Aguascalientes,2005,1,Mujeres,28430,145656,19.518591750000000000000
Baja California,2005,1,Hombres,167651,768989,21.801482210000000000000
...,...,...,...,...,...,...
Veracruz,2022,1,Mujeres,107640,1190733,9.0398099320000000000000
Yucat n,2022,1,Hombres,101992,691397,14.751582670000000000000
Yucat n,2022,1,Mujeres,82759,478943,17.279509250000000000000
Zacatecas,2022,1,Hombres,44105,402326,10.962503040000000000000
Zacatecas,2022,1,Mujeres,39472,255761,15.43315830000000000000

In [ ]:
#paso2: aplicamos filtro de filas vs columnas 
filtro4= df.loc[["Puebla","Oaxaca","Veracruz","Guerrero"],["Poblacion_ocupada_en_la_industria_manufacturera"]]
filtro4

In [24]:
#filtro por cabecera
filtro5=df.head()
filtro5

,Periodo,Trimestre,Sexo,Poblacion_ocupada_en_la_industria_manufacturera,Poblaci n_ocupada,Tasa_de_ocupaci n_en_la_industria_manufacturera
Entidad_Federativa,,,,,,
Nacional,2005,1,Hombres,4384907,26597801,16.485975660000000000000
Nacional,2005,1,Mujeres,2690296,14843275,18.124679360000000000000
Aguascalientes,2005,1,Hombres,56407,246177,22.913188480000000000000
Aguascalientes,2005,1,Mujeres,28430,145656,19.518591750000000000000
Baja California,2005,1,Hombres,167651,768989,21.801482210000000000000

FILTROS BASICOS PARA VARIABLES CUANTITATIVAS

In [25]:
#filtro por comparacion 
filtro6= df[df["Periodo"] > 2006]
filtro6

,Periodo,Trimestre,Sexo,Poblacion_ocupada_en_la_industria_manufacturera,Poblaci n_ocupada,Tasa_de_ocupaci n_en_la_industria_manufacturera
Entidad_Federativa,,,,,,
Nacional,2007,1,Hombres,4495811,27286572,16.476276320000000000000
Nacional,2007,1,Mujeres,2798066,16239553,17.229944690000000000000
Aguascalientes,2007,1,Hombres,59177,263092,22.492892220000000000000
Aguascalientes,2007,1,Mujeres,31485,162275,19.402249270000000000000
Baja California,2007,1,Hombres,160967,784303,20.523573160000000000000
...,...,...,...,...,...,...
Veracruz,2022,1,Mujeres,107640,1190733,9.0398099320000000000000
Yucat n,2022,1,Hombres,101992,691397,14.751582670000000000000
Yucat n,2022,1,Mujeres,82759,478943,17.279509250000000000000
Zacatecas,2022,1,Hombres,44105,402326,10.962503040000000000000
Zacatecas,2022,1,Mujeres,39472,255761,15.43315830000000000000